"""empty message

Revision ID: 8b75b31bdb0f
Revises: e04da091bbaa
Create Date: 2022-05-23 02:20:31.299730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b75b31bdb0f'
down_revision = 'fc3829a6a579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle') as batch_op:
        batch_op.drop_column('similarWords')
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    op.add_column('puzzle', sa.Column('similarWords', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
