"""user and puzzle table

Revision ID: 8db710f4c571
Revises: 
Create Date: 2022-05-21 21:17:10.170886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db710f4c571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('wordType', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.String(length=256), nullable=True),
    sa.Column('sentence', sa.String(length=256), nullable=True),
    sa.Column('similarWords', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzle_word'), 'puzzle', ['word'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('gamesPlayed', sa.Integer(), nullable=True),
    sa.Column('gamesWon', sa.Integer(), nullable=True),
    sa.Column('totalGuesses', sa.Integer(), nullable=True),
    sa.Column('currentStreak', sa.Integer(), nullable=True),
    sa.Column('bestStreak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_puzzle_word'), table_name='puzzle')
    op.drop_table('puzzle')
    # ### end Alembic commands ###
