"""empty message

Revision ID: bbda6057e65b
Revises: 8db710f4c571
Create Date: 2022-05-22 22:48:07.432220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbda6057e65b'
down_revision = '8db710f4c571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'similarWords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('similarWords', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
