"""empty message

Revision ID: fc3829a6a579
Revises: bbda6057e65b
Create Date: 2022-05-22 23:06:00.585103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3829a6a579'
down_revision = 'bbda6057e65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('todayGuesses', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('todayCorrect', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'todayCorrect')
    op.drop_column('user', 'todayGuesses')
    # ### end Alembic commands ###
